<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProdukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kategoris = DB::table('kategoris')->pluck('idkategori', 'nama');

        DB::table('produks')->insert([
            // Kategori Pakaian
            [
                'barcode' => '8991234567890',
                'nama' => 'Kaos Polos Hitam',
                'harga' => 85000,
                'stok' => 50,
                'gambar' => 'images/default.png',
                'usia_awal' => Carbon::now()->subYears(10),
                'usia_akhir' => Carbon::now()->addYears(50),
                'kategori_idkategori' => $kategoris['Pakaian'] ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'barcode' => '8991234567891',
                'nama' => 'Kaos Polos Putih',
                'harga' => 85000,
                'stok' => 45,
                'gambar' => 'images/default.png',
                'usia_awal' => Carbon::now()->subYears(10),
                'usia_akhir' => Carbon::now()->addYears(50),
                'kategori_idkategori' => $kategoris['Pakaian'] ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'barcode' => '8991234567892',
                'nama' => 'Kemeja Lengan Panjang',
                'harga' => 150000,
                'stok' => 30,
                'gambar' => 'images/default.png',
                'usia_awal' => Carbon::now()->subYears(10),
                'usia_akhir' => Carbon::now()->addYears(50),
                'kategori_idkategori' => $kategoris['Pakaian'] ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'barcode' => '8991234567893',
                'nama' => 'Celana Jeans Pria',
                'harga' => 250000,
                'stok' => 25,
                'gambar' => 'images/default.png',
                'usia_awal' => Carbon::now()->subYears(10),
                'usia_akhir' => Carbon::now()->addYears(50),
                'kategori_idkategori' => $kategoris['Pakaian'] ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'barcode' => '8991234567894',
                'nama' => 'Jaket Hoodie',
                'harga' => 180000,
                'stok' => 20,
                'gambar' => 'images/default.png',
                'usia_awal' => Carbon::now()->subYears(10),
                'usia_akhir' => Carbon::now()->addYears(50),
                'kategori_idkategori' => $kategoris['Pakaian'] ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'barcode' => '8991234567895',
                'nama' => 'Dress Wanita',
                'harga' => 220000,
                'stok' => 15,
                'gambar' => 'images/default.png',
                'usia_awal' => Carbon::now()->subYears(10),
                'usia_akhir' => Carbon::now()->addYears(50),
                'kategori_idkategori' => $kategoris['Pakaian'] ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'barcode' => '8991234567896',
                'nama' => 'Rok Mini',
                'harga' => 95000,
                'stok' => 8,
                'gambar' => 'images/default.png',
                'usia_awal' => Carbon::now()->subYears(10),
                'usia_akhir' => Carbon::now()->addYears(50),
                'kategori_idkategori' => $kategoris['Pakaian'] ?? 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Kategori Makanan
            [
                'barcode' => '8992234567890',
                'nama' => 'Indomie Goreng',
                'harga' => 3500,
                'stok' => 200,
                'gambar' => 'images/default.png',
                'usia_awal' => Carbon::now()->subYears(5),
                'usia_akhir' => Carbon::now()->addYears(80),
                'kategori_idkategori' => $kategoris['Makanan'] ?? 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'barcode' => '8992234567891',
                'nama' => 'Mie Sedaap Soto',
                'harga' => 3000,
                'stok' => 180,
                'gambar' => 'images/default.png',
                'usia_awal' => Carbon::now()->subYears(5),
                'usia_akhir' => Carbon::now()->addYears(80),
                'kategori_idkategori' => $kategoris['Makanan'] ?? 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'barcode' => '8992234567892',
                'nama' => 'Chitato Rasa Sapi Panggang',
                'harga' => 12000,
                'stok' => 75,
                'gambar' => 'images/default.png',
                'usia_awal' => Carbon::now()->subYears(5),
                'usia_akhir' => Carbon::now()->addYears(80),
                'kategori_idkategori' => $kategoris['Makanan'] ?? 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'barcode' => '8992234567893',
                'nama' => 'Oreo Vanilla',
                'harga' => 15000,
                'stok' => 60,
                'gambar' => 'images/default.png',
                'usia_awal' => Carbon::now()->subYears(5),
                'usia_akhir' => Carbon::now()->addYears(80),
                'kategori_idkategori' => $kategoris['Makanan'] ?? 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'barcode' => '8992234567894',
                'nama' => 'Pocky Chocolate',
                'harga' => 18000,
                'stok' => 55,
                'gambar' => 'images/default.png',
                'usia_awal' => Carbon::now()->subYears(5),
                'usia_akhir' => Carbon::now()->addYears(80),
                'kategori_idkategori' => $kategoris['Makanan'] ?? 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'barcode' => '8992234567895',
                'nama' => 'Teh Kotak Melati',
                'harga' => 7000,
                'stok' => 100,
                'gambar' => 'images/default.png',
                'usia_awal' => Carbon::now()->subYears(5),
                'usia_akhir' => Carbon::now()->addYears(80),
                'kategori_idkategori' => $kategoris['Makanan'] ?? 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'barcode' => '8992234567896',
                'nama' => 'Aqua 600ml',
                'harga' => 5000,
                'stok' => 150,
                'gambar' => 'images/default.png',
                'usia_awal' => Carbon::now()->subYears(5),
                'usia_akhir' => Carbon::now()->addYears(80),
                'kategori_idkategori' => $kategoris['Makanan'] ?? 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'barcode' => '8992234567897',
                'nama' => 'Coca Cola 390ml',
                'harga' => 8000,
                'stok' => 90,
                'gambar' => 'images/default.png',
                'usia_awal' => Carbon::now()->subYears(5),
                'usia_akhir' => Carbon::now()->addYears(80),
                'kategori_idkategori' => $kategoris['Makanan'] ?? 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'barcode' => '8992234567898',
                'nama' => 'Energen Coklat',
                'harga' => 2500,
                'stok' => 120,
                'gambar' => 'images/default.png',
                'usia_awal' => Carbon::now()->subYears(5),
                'usia_akhir' => Carbon::now()->addYears(80),
                'kategori_idkategori' => $kategoris['Makanan'] ?? 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'barcode' => '8992234567899',
                'nama' => 'Kopi Kapal Api',
                'harga' => 2000,
                'stok' => 5,
                'gambar' => 'images/default.png',
                'usia_awal' => Carbon::now()->subYears(5),
                'usia_akhir' => Carbon::now()->addYears(80),
                'kategori_idkategori' => $kategoris['Makanan'] ?? 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
